#Replace with your own keys, these keys are already deprecated
OPENAI_API_KEY = "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"
GOOGLE_API_KEY = "AIzaSyBPGkvYUXaCJltRV0ti-jL-LMdOmaoX1GY"