critique:
  prompt:
    PROMPT_PATH: "prompt_files/critique"
    CRITIQUE_RESOLUTION_PROMPT: "critique_resolution_fewshot.jinja"

ir:
  prompt:
    PROMPT_PATH: "prompt_files/information_retriever"
    BASELINE_ZEROSHOT_PROMPT: "zeroshot_baseline_ir.jinja"
    BASELINE_AFTER_CRITIQUE_ZEROSHOT_PROMPT: "zero_shot_baseline_after_critique_ir.jinja"
  dense_fusion:
    RAW_POI_PATH_TEST: "information_retriever/database/raw_poi_test"
    VECTOR_DATABASE_PATH : "information_retriever/database/vector_database"

planning:
  prompt:
    PROMPT_PATH: "prompt_files/planner"
    BASELINE_ZEROSHOT_PROMPT: "zeroshot_baseline_planner.jinja"
    BASELINE_ZEROSHOT_AFTER_CRITIQUE_PROMPT: "zero_shot_baseline_planner_after_critique.jinja"
    ONE_STEP_BASELINE_ZEROSHOT_PROMPT: "one_step_zeroshot_baseline_planner.jinja"

user_intent:
  prompt:
    PROMPT_PATH: "prompt_files/user_intent"
    ASK_FOR_RECOMMENDATION: "ask_for_recommendation.jinja"
    PROVIDE_PREFERENCE: "provide_preference.jinja"
    CUT_OFF_INPUT: "cut_off_input.jinja"

query_processor:
  prompt:
    PROMPT_PATH: "prompt_files/query_processor"
    ZEROSHOT_ASPECT_EXTRACTION: "zeroshot_aspect_extraction.jinja"

geo_processor:
  google:
    BASE_URL: "https://maps.googleapis.com/maps/api/geocode/json"

reasoner:
  prompt:
    PROMPT_PATH: "prompt_files/reasoner"
    POI_KEYWORD_SUMMARIZATION: "poi_keyword_summarization.jinja"
    POI_KEYWORD_SUMMARIZATION_AFTER_CRITIQUE: "poi_keyword_summarization_after_critique.jinja"
    TRIP_SUMMARIZATION: "trip_summarization.jinja"
    TRIP_SUMMARIZATION_AFTER_CRITIQUE: "trip_summarization_after_critique.jinja"

web_search:
  google:
    CX: "a19f3b2e14e6e436b"
    BASE_URL: "https://www.googleapis.com/customsearch/v1"
    API_KEY: "AIzaSyCbWt8HLsCj3q2vzCQyJNWbjFRtoWkEAP0"

event_processor:
  prompt:
    PROMPT_PATH: "prompt_files/event_processor"
    EVENT_SUMMARIZATION: "event_summarization.jinja"
